Task 01
IgorSinitsa/test-guru pull request #1
Opened 2024-08-07 16:31 UTC by IgorSinitsa

Прошу высказать свои замечания

2024-08-08 05:22 UTC, VidgarVii requested changes

2024-08-08 05:22 UTC, VidgarVii commented on README.md
> +  Класс Difficulty(сложность, Test)
Сложность будет атрибутом теста. Сущность не нужна

2024-08-08 05:22 UTC, VidgarVii commented on config/application.rb
> +    I18n.load_path += Dir[Rails.root.join("lib", "locale", "*.{rb,yml}")]
это для чего нужно?

2024-08-08 05:22 UTC, VidgarVii commented on config/application.rb
> +    I18n.default_locale = :ru
для единообразия кода лучше обращаться к конфигу
`config.i18n.default_locale = `

2024-08-08 05:22 UTC, VidgarVii commented on config/initializers/version.rb
> +  # можно еще как VERSION = '0.1.0'
лучше статические данные как раз хранить в константе

2024-08-08 05:22 UTC, VidgarVii commented on config/initializers/version.rb
> +end
тут бардак с отступами

2024-08-08 05:22 UTC, VidgarVii commented on public/about.html
> +      <a href="http://thinknetica.com" target="_blank">Thinknetica</a>
ссылки на сторонние ресурсы правильно открывать в новой вкладке и хорошо бы добавить опцию rel=nofollow rel=noopener. Так клиента сохраним и поискового робота дальше не пустим

2024-08-09 13:19 UTC, IgorSinitsa commented on README.md
> +  Класс Difficulty(сложность, Test)
Изменил

2024-08-09 13:21 UTC, IgorSinitsa commented on config/application.rb
> +    I18n.load_path += Dir[Rails.root.join("lib", "locale", "*.{rb,yml}")]
Добавил пути для файлов перевода.
Потом почитал внимательно и обратил внимание на дефолтный путь config/locales который уже присутствует

2024-08-09 13:21 UTC, IgorSinitsa commented on config/application.rb
> +    I18n.default_locale = :ru
исправил

2024-08-09 13:22 UTC, IgorSinitsa commented on config/initializers/version.rb
> +  # можно еще как VERSION = '0.1.0'
исправил

2024-08-09 13:22 UTC, IgorSinitsa commented on config/initializers/version.rb
> +end
моя вина скомитил, а потом причесал(

2024-08-09 13:23 UTC, IgorSinitsa commented on public/about.html
> +      <a href="http://thinknetica.com" target="_blank">Thinknetica</a>
добавил
rel="noopener noreferrer nofollow"

2024-08-10 10:03 UTC, VidgarVii requested changes

2024-08-10 10:03 UTC, VidgarVii commented on config/initializers/version.rb
> +    def version
в этом методе нет необходимости. К константе можно и без метода без проблем  обратиться если объявить её в классе Application

2024-08-10 10:03 UTC, VidgarVii commented on config/application.rb
> +    config.I18n.default_locale = :ru
чтобы не было ошибок в системе, надо еще добавить файл конфигураций в папку config/locales ru.yml. Содержание почти аналогичное как en.yml

2024-08-10 15:35 UTC, merged