base for task02
IgorSinitsa/test-guru pull request #2
Opened 2024-08-12 14:11 UTC by IgorSinitsa

Миграция для проверки

2024-08-13 04:56 UTC, VidgarVii requested changes

2024-08-13 04:56 UTC, VidgarVii commented on .gitignore
> +# /db/*.sqlite3
файлы бд в репозиторий лучше не класть

2024-08-13 04:56 UTC, VidgarVii commented on Gemfile
> +gem "i18n", "~> 1.14", ">= 1.14.1"
эти 2 гема не особо то и нужны.
i18n встраен в rails
base64 встроен в ruby

2024-08-13 04:56 UTC, VidgarVii commented on db/migrate/20240812131406_change_column_default.rb
> +    change_column_default :tests, :level, from: nil, to: 1
не стоит добавлять отдельные миграции для изменения полей в одном ПР. Миграции всегда являются опасным местом в ПО. Так как меняют схему базы. И всегда стараются минимизировать кол-во миграций.
В этом ДЗ надо создать 5 моделей и 5 таблиц. Значит у тебя должно быть 5 миграций. Прописывай все нужные опции полям сразу. Все остальные миграции являются обычным оверхедом

Пример
```
t.string :title, null: false 
```
Большое кол-во миграций увеличивает время развёртывания ПО. Так же миграция является местом риска, так как может сломать существующую базу. Еще они имеют свойство протухать и быть не актуальными или не рабочими. По этому всегда стараются минимизировать кол-во миграций.

2024-08-13 04:57 UTC, VidgarVii commented
нет актуальной схемы бд.. Из-за большого кол-ва миграций сложно понять что в итоге получится в бд. И работают ли сами миграции. Всегда когда ПР содержит новые миграции нужна актуальная схема бд.

2024-08-13 09:29 UTC, IgorSinitsa commented on .gitignore
> +# /db/*.sqlite3
Закрыл

2024-08-13 09:30 UTC, IgorSinitsa commented on Gemfile
> +gem "i18n", "~> 1.14", ">= 1.14.1"
Понял.

2024-08-13 09:32 UTC, IgorSinitsa commented on db/migrate/20240812131406_change_column_default.rb
> +    change_column_default :tests, :level, from: nil, to: 1
Грубо говоря одна модель = одна миграция,
дополнительные миграции, чтоб был нормальный откат, в случае чего,  Так?

2024-08-13 17:13 UTC, VidgarVii requested changes

2024-08-13 17:13 UTC, VidgarVii commented on Gemfile
> +gem "i18n", "~> 1.14", ">= 1.14.1"
т.е. можно и лучше эти гемы убрать

2024-08-13 17:13 UTC, VidgarVii commented on app/models/answer.rb
> +  belongs_to :question
ассоциации сейчас точно не нужны. И они не корректны. Потом, когда будут по ним урок, их сделаем правильно

2024-08-13 17:13 UTC, VidgarVii commented on db/migrate/20240812131406_change_column_default.rb
> +    change_column_default :tests, :level, from: nil, to: 1
одна модель = одна миграция
ни каких дополнительных миграций не нужно делать в этом ПР

2024-08-13 17:13 UTC, VidgarVii commented on db/schema.rb
> +    t.boolean "correct", default: true
для логических полей рекомендуется указывать опцию `null: false`
тогда в базе будут возможны строго два значения `true` или `false` вместо трех (`null/true/false`)

2024-08-13 17:13 UTC, VidgarVii commented on db/schema.rb
> +    t.integer "level", default: 1
null: false

2024-08-13 17:13 UTC, VidgarVii commented on db/schema.rb
> +end
для теста нам еще понадобиться автор. Это юзер который создал тест. Но при этом по названию колонки должно быть понятно, что речь идёт именно об авторе теста. Предлагаю это сделать в текущем ПР.

2024-08-14 10:52 UTC, IgorSinitsa commented on db/migrate/20240812131406_change_column_default.rb
> +    change_column_default :tests, :level, from: nil, to: 1
Вопрос скорей к базе данных.
Я правильно понимаю, хоть мы сделали ветку git, но развлекаться мы продолжаем с текущей базой?
Если так то, по идее правильно будет делать копию базы и подключаться уже к ней?
Или есть еще какие приемы при работе с базой, если используешь ветки git

2024-08-14 16:00 UTC, VidgarVii requested changes

2024-08-14 16:00 UTC, VidgarVii commented on db/migrate/20240814101731_add_key_t_table.rb
> +    add_reference(:tests, :author, foreign_key: { to_table: :users })
это лучше сделать сразу при создании таблицы тесты

2024-08-14 16:00 UTC, VidgarVii commented on db/migrate/20240814084913_create_tests.rb
> +      t.references :category
у теста обязательно должна быть категория. Это так же относится ко всем связям

2024-08-14 16:00 UTC, VidgarVii commented on db/migrate/20240814084913_create_tests.rb
> +      t.references :category
так же надо обязательно прописывать внешний ключ, аттрибутом foreign_key: true

2024-08-14 19:45 UTC, VidgarVii requested changes

2024-08-14 19:45 UTC, VidgarVii commented on db/migrate/20240814084913_create_tests.rb
> +  end
```
t.references :category, null: false, foreign_key: true
t.references :author, null: false, foreign_key: { to_table: :users }
```

и так везде стоит поправить создания связи в блоке create_table

2024-08-15 09:59 UTC, merged