base task05
IgorSinitsa/test-guru pull request #5
Opened 2024-08-19 13:35 UTC by IgorSinitsa

На проверку

2024-08-19 17:59 UTC, BubuntuClu requested changes

2024-08-19 17:59 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :category, ->(category) {
сортировку и выборку не надо помещать в скоуп.
скоуп должен возвращать объект ActiveRecord::Relation, pluck возвращает массив.
так же скоуп это универсальный метод, который может использован в разных частях приложения, там может потребоваться другая сортировка и выборка.
метод надо оставить, заменить часть выражения на скоуп и уже к скоупу применить сортировку и выборку

2024-08-19 18:30 UTC, IgorSinitsa commented on app/models/user.rb
> +  scope :test_level, ->(level) { tests.where(level: level) }
![11](https://github.com/user-attachments/assets/b004dc52-6a1a-44ed-81c1-7b23170d9c7b)

2024-08-19 18:31 UTC, IgorSinitsa commented on app/models/answer.rb
> +    errors.add(:body) if count >= 4
![22](https://github.com/user-attachments/assets/c16ad292-85fb-43e3-a585-7c0cb4167c0b)

2024-08-19 18:36 UTC, IgorSinitsa commented on app/models/user.rb
> +  scope :test_level, ->(level) { tests.where(level: level) }
Проблема простая, я работаю на винде с VS Code, файлы локально и пересылаю на докер
Тестовое крутится в докере на хостинге, тест и, проверка. Бывает путаюсь какие отправил файлы с локального.
Постараюсь больше таких не делать ошибок.
Пока отлаживаю взаимодействие докера и VScode

2024-08-19 18:39 UTC, IgorSinitsa commented on app/models/test.rb
> +                    uniqueness: { scope: :title }
Это понятно, я так понял, из задания, что надо сделать проверку только в моделях.
Добавить на базе, значит добавлю

2024-08-19 18:44 UTC, IgorSinitsa commented on app/models/result.rb
> +                      uniqueness: { scope: :user_id }
Вопрос при update , разве условие будет срабатывать?
а если поставить on create?
Интересно просто

2024-08-22 17:04 UTC, BubuntuClu commented on app/models/user.rb
> +    User.test_level(level)
подсказка - ни один из написанных

2024-08-22 17:05 UTC, BubuntuClu commented on app/models/answer.rb
> +    errors.add(:body) if count >= 4
вообще я тут ожидал другую ошибку, а не просто роллбэк операции.
ожидал что будет ругаться на `count`, потому что рельса не знает что это такое. нигде не было объявлено такой переменной и это не метод объекта

2024-08-23 18:11 UTC, merged