base task07
IgorSinitsa/test-guru pull request #7
Opened 2024-08-30 12:54 UTC by IgorSinitsa

На проверку

2024-10-11 17:51 UTC, BubuntuClu requested changes

2024-10-11 17:51 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +  def check_result_test(user, test)
этот метод для чего?

2024-10-11 17:51 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    end
чем больше смотрю на метод, тем больше вопросов возникает) тут каждая строка это шедевр)

но основной вопрос что делает этот метод? он нигде не используется

2024-10-11 17:51 UTC, BubuntuClu commented on app/helpers/result_helper.rb
> +    "Questions № #{result.total_questions - result.questions.count + 2} #{result.current_question.body} question"
есть метод `index` у коллекции, используй его чтобы найди индекс текущего вопроса.

не надо создавать доп поле для хранения списка вопросов.

почему +2 надо добавлять?

2024-10-11 17:51 UTC, BubuntuClu commented on app/controllers/result_controller.rb
> +  end
можно же со страницы теста еще раз начать тест, зачем делать отдельный метод?
и отдельное поле под попытки заводить? количество строк в таблице с одинаковым `user_id/test_id` и есть количество попыток

2024-10-11 17:51 UTC, BubuntuClu commented on app/models/result.rb
> +      add_current_question
> Сделайте назначение следующего вопроса в модели TestPassage с помощью обратного вызова

это не сделал

2024-10-11 17:51 UTC, BubuntuClu commented on app/models/result.rb
> +  def accept!(answer_ids)
этот метод должен только принять правильные ответы. у тебя тут очень много всего просходит.  ниндзя метод какой-то получился

2024-10-11 17:51 UTC, BubuntuClu commented on app/models/result.rb
> +  def before_validation_set_questions
получать первый и след вопрос надо через запросы к БД и через активрекорд. тут код написано в C стиле чтоли.

2024-10-11 17:51 UTC, BubuntuClu commented on db/migrate/20241004162534_add_question_to_results.rb
> +      t.integer :attempts, null: false, default: 0
это лишнее поле. каждая запись в таблице и есть попытка

2024-10-11 17:51 UTC, BubuntuClu commented on db/migrate/20241004162534_add_question_to_results.rb
> +      t.integer :total_questions, null: false, default: 0
это поле не нужно. зачем в прохождениях хранить количество вопросов, оно есть в тесте, который ты сюда не добавил. 

в прохождении надо знать кто проходил, что проходил, как успешно прошел. ну и текущий вопрос отслеживать чтобы понять закончил или нет

2024-10-11 17:51 UTC, BubuntuClu commented on config/routes.rb
> +      get :again
сомнительный метод. кажется, его можно выпилить

2024-10-11 17:51 UTC, BubuntuClu commented on config/routes.rb
> +      resources :answers, shallow: true
что дает тебе опция `shallow: true` для ответов?

2024-10-11 17:51 UTC, BubuntuClu commented on app/views/result/show.html.erb
> +  <%= render "form" %>
тут усложнение логики случилось. в одну вьюху размещаешь разные кейсы использования - прохождение теста и отображение резльутатов. сделай просто разные роуты и вьюху под каждый.

2024-10-11 17:51 UTC, BubuntuClu commented on app/views/result/show.html.erb
> +<% if @result.questions[0] == 0 %>
если вьюхи распилишь, тогда этот костыль можно будет убрать

2024-10-11 17:51 UTC, BubuntuClu commented on app/views/result/_scope.html.erb
> +<% cl = @result.point > 85 ? "success" : "fail" %>
что такое 85? без контекста это магическое число. помести это число в модель в константу, обзови понятно. сделай в модели метод `success?` и тут вызывай его

что такое `cl`? ты вместе не ограничен, пиши понятные говорящие имена переменных/методов

2024-10-11 17:51 UTC, BubuntuClu commented on app/models/result.rb
> +  def add_poins
стоит ли считать на каждый вопрос сколько поинтов? как будто имеет смысл только один раз их считать, когда тест окончен

2024-10-11 17:51 UTC, BubuntuClu commented on app/helpers/result_helper.rb
> +    if result.point >= 85
вот о5 магическое число. тут бы тебе тоже пригодился метод `result.success?`

2024-10-11 17:51 UTC, BubuntuClu commented on app/helpers/result_helper.rb
> +    if result.point >= 85
и в целом стоит подумать как за одну проверку успеха показать нужный цвет и текст

2024-10-11 20:03 UTC, IgorSinitsa commented on app/controllers/tests_controller.rb
> +    end
Забыл удалить. Мысли в слух.
Не захотелось постоянно добавлять новые строки теста.
А так можно начинать, с того места, где закончил, делать перетасовывать вопросы, выбирать любое количество вопросов из общего количества. Вопросов может быть 100, но задает например 30 и в любом порядке.

2024-10-11 20:22 UTC, IgorSinitsa commented on app/controllers/result_controller.rb
> +  end
Ну это мое мнение, множество записей нагружает таблицу, на выборку. Плюс выбирать пройдена последняя или нет. формирование статистики. Но опять это сугубо мое мнение и решение

2024-10-11 20:24 UTC, IgorSinitsa commented on app/models/result.rb
> +      add_current_question
исправлю

2024-10-12 06:38 UTC, BubuntuClu commented on app/controllers/result_controller.rb
> +  end
тут у тебя получается, что ты "упрощаешь" жизнь БД, но усложняешь бизнес-логику.
БД рассчитана на то чтобы работать с большими обьемами данных, у нее для этого есть свои алгоритмы оптимизации, индексы навесить можно, партицирование/шардирование. это как раз ее работа с данными работать

2024-10-12 06:41 UTC, BubuntuClu commented on app/helpers/result_helper.rb
> +    "Questions № #{result.total_questions - result.questions.count + 2} #{result.current_question.body} question"
вот они, привычки низкоуровневых языков)
без понимания алгоритма не понятно почему ты +2 добавляешь. обычно это +1, так как индекс отличается в массивах.

нужно магические числа помещать в константы с понятными обозначениями

ну и на счет лишний раз не дергать. рельса кеширует запросы, если ты на уровне контроллера достал все вопросы теста, то она уже в памяти их имеет. второй раз не бдует их выгружать. и тут есть нюанс связанный с `count`. https://medium.com/unagi/ruby-on-rails-length-vs-size-vs-count-with-examples-a32e17274c79 тут можно ознакомиться, твоя экономия с этим методом работать не будет

2024-10-12 06:42 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    end
такой функционал в учебном прилоежнии не закладывается

2024-10-13 17:15 UTC, IgorSinitsa commented on app/helpers/result_helper.rb
> +    "Questions № #{result.total_questions - result.questions.count + 2} #{result.current_question.body} question"
У меня count опрашивает не количество записей, а количество элементов в массиве, которое хранится в записи (памяти), вначале я снял id записей и поместил в память с ними и апперирую.
Но за статью большое спасибо , интересные нюансы

2024-10-13 17:17 UTC, IgorSinitsa commented on app/controllers/tests_controller.rb
> +    end
Сила привычки, меня учили когда пишешь код, думай как функционал будет развиваться, чтоб заложить доп. возможности. Ну тут увы по другому не получается))

2024-10-13 17:47 UTC, BubuntuClu commented on app/controllers/result_controller.rb
> +      @result.save
сохранение можно было оставить внутри метода принятия ответов. бех сохранения по сути ничего не происходит в методе

2024-10-13 17:47 UTC, BubuntuClu commented on app/helpers/result_helper.rb
> +      _class = "success"
нижним подчеркиванием в руби поменятся переменная, которая не используется в методе

2024-10-13 17:47 UTC, BubuntuClu commented on app/models/result.rb
> +  def set_current_question
```
 def set_next_or_first_question
    if persisted?
      self.current_question = test.questions.order(:id).where('id > ?', current_question.id).first
    else
       self.current_question = test.questions.first 
    end
  end
```
как-то так можно написать чтобы ставить первый/след вопрос у теста

2024-10-20 16:50 UTC, merged